'use client'

import { useState } from 'react'
import { ArrowRight, Camera, Check, ChevronLeft, CircleUserRound, Clock3, Eye, Heart, Leaf, Menu, Pencil, Search, Send, ShieldCheck, Star, Upload, X } from 'lucide-react'

type View = 'blog' | 'post' | 'login' | 'signup' | 'new' | 'admin'

type Post = { id: string; title: string; excerpt: string; category: string; author: string; date: string; read: string; image: string; rating: number; featured?: boolean }

const posts: Post[] = [
  { id: 'elephants', title: 'The Gentle Giants of Udawalawe', excerpt: 'A morning among Sri Lanka’s most iconic residents, and what their quiet rituals teach us about wild places.', category: 'Wildlife', author: 'Nimali Perera', date: 'May 14, 2024', read: '6 min read', rating: 4.9, featured: true, image: 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=1400&q=85' },
  { id: 'safari', title: 'A First-Timer’s Guide to Safari', excerpt: 'Everything you need to know before your first sunrise drive through the park.', category: 'Travel tips', author: 'Ruwan Silva', date: 'May 08, 2024', read: '8 min read', rating: 4.8, image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=900&q=85' },
  { id: 'monsoon', title: 'When the Rains Arrive', excerpt: 'The green season transforms Udawalawe into a different kind of wilderness.', category: 'Seasons', author: 'Ayesha Fernando', date: 'Apr 22, 2024', read: '5 min read', rating: 4.7, image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=900&q=85' },
  { id: 'birds', title: 'Birdsong at the Water’s Edge', excerpt: 'Meet the feathered residents that make every quiet lake feel alive.', category: 'Birds', author: 'Dilan Jayasinghe', date: 'Apr 10, 2024', read: '4 min read', rating: 4.9, image: 'https://images.unsplash.com/photo-1444464666168-49d633b86797?auto=format&fit=crop&w=900&q=85' },
]

function Rating({ value, large = false }: { value: number; large?: boolean }) { return <div className={`rating ${large ? 'rating-large' : ''}`} aria-label={`${value} out of 5 stars`}>{[1,2,3,4,5].map(i => <Star key={i} size={large ? 17 : 13} fill={i <= Math.round(value) ? 'currentColor' : 'none'} />)} <span>{value}</span></div> }

function Header({ go }: { go: (v: View) => void }) {
  return <header className="site-header"><div className="nav-wrap"><button className="brand" onClick={() => go('blog')}><span className="brand-mark"><Leaf size={18}/></span><span>UDAWALAWE<br/><em>WILD</em></span></button><nav><button className="active" onClick={() => go('blog')}>Stories</button><button onClick={() => go('new')}>Share a story</button><button onClick={() => go('admin')}>For editors</button></nav><div className="nav-actions"><button className="icon-button" aria-label="Search"><Search size={18}/></button><button className="text-link" onClick={() => go('login')}>Sign in</button><button className="pill-button small" onClick={() => go('signup')}>Join the community</button><button className="menu-button" aria-label="Menu"><Menu size={20}/></button></div></div></header>
}

function BlogCard({ post, go }: { post: Post; go: (v: View) => void }) { return <article className={`blog-card ${post.featured ? 'featured-card' : ''}`}><button className="image-button" onClick={() => go('post')}><img src={post.image} alt=""/><span className="category-tag">{post.category}</span></button><div className="card-copy"><div className="meta"><span>{post.date}</span><span>·</span><span>{post.read}</span></div><button className="card-title" onClick={() => go('post')}>{post.title}</button><p>{post.excerpt}</p><div className="card-footer"><span className="author"><span className="avatar">{post.author.charAt(0)}</span> {post.author}</span><Rating value={post.rating}/></div></div></article> }

function BlogListing({ go }: { go: (v: View) => void }) { return <><section className="hero"><div><p className="eyebrow"><span className="eyebrow-line"/> Field notes from Sri Lanka</p><h1>Stories from<br/><i>the wild.</i></h1><p className="hero-copy">A community journal for curious travelers, devoted naturalists, and everyone who feels most at home under an open sky.</p><button className="outline-button" onClick={() => document.getElementById('stories')?.scrollIntoView({ behavior: 'smooth' })}>Explore the stories <ArrowRight size={16}/></button></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1535338454770-8be927b5a00b?auto=format&fit=crop&w=1200&q=85" alt="Elephant walking through a Sri Lankan landscape"/><div className="image-caption"><Camera size={14}/> Udawalawe National Park · Sri Lanka</div></div></section><main id="stories" className="listing"><div className="section-heading"><div><p className="eyebrow">The journal</p><h2>Latest stories</h2></div><div className="filters"><button className="filter active">All stories</button><button className="filter">Wildlife</button><button className="filter">Travel tips</button><button className="filter">Conservation</button></div></div><div className="post-grid">{posts.map(post => <BlogCard key={post.id} post={post} go={go}/>)}</div><div className="join-banner"><div><p className="eyebrow">Your turn</p><h3>Seen something<br/><i>worth sharing?</i></h3></div><p>Every story helps us see this place a little more clearly. Share your field notes with the community.</p><button className="dark-button" onClick={() => go('new')}>Share a story <ArrowRight size={16}/></button></div></main></> }

function PostDetail({ go }: { go: (v: View) => void }) { const post = posts[0]; return <main className="post-detail"><button className="back-link" onClick={() => go('blog')}><ChevronLeft size={16}/> Back to all stories</button><div className="detail-header"><div><span className="category-tag static">{post.category}</span><h1>{post.title}</h1><p className="detail-dek">A morning among Sri Lanka’s most iconic residents, and what their quiet rituals teach us about wild places.</p><div className="detail-byline"><span className="avatar large">N</span><div><strong>{post.author}</strong><span>{post.date} · {post.read}</span></div><Rating value={post.rating} large/></div></div><img src={post.image} alt="Elephant walking in Udawalawe"/></div><div className="article-layout"><article className="article-body"><p className="lead">At 6:12 on a cool September morning, the first elephant appeared through the mist. She was older, deliberate, and entirely unhurried.</p><p>Udawalawe is known for its elephants. But to call them an attraction is to miss the point. They are the park’s original residents, moving through the grasslands with a patience that makes our own hurried lives feel slightly absurd.</p><blockquote>“The best sightings are not the dramatic ones. They are the quiet moments when the wild forgets you are there.”</blockquote><p>We watched her family gather at the water’s edge. A calf leaned into its mother; a tusker stood guard beneath a rain tree. Then, as softly as they had arrived, they disappeared into the green.</p><div className="article-note"><Leaf size={19}/><span><strong>Leave no trace</strong><br/>Keep a respectful distance and never feed wildlife.</span></div></article><aside className="review-card"><h3>Have you been here?</h3><p>Share your experience with fellow explorers.</p><button className="dark-button full" onClick={() => go('login')}>Write a review <Pencil size={15}/></button><div className="review-divider"/><div className="review-stat"><strong>4.9</strong><Rating value={4.9} large/><span>Based on 28 reviews</span></div></aside></div></main> }

function Auth({ signup, go }: { signup?: boolean; go: (v: View) => void }) { return <main className="auth-page"><div className="auth-art"><img src="https://images.unsplash.com/photo-1534567110243-8875d64ca8ff?auto=format&fit=crop&w=1200&q=85" alt="Wild elephant in the forest"/><div><span className="brand-mark"><Leaf size={18}/></span><p>Join a community<br/><i>that looks closer.</i></p></div></div><div className="auth-form"><button className="back-link" onClick={() => go('blog')}><ChevronLeft size={16}/> Back to stories</button><div className="form-inner"><p className="eyebrow">{signup ? 'Become a contributor' : 'Welcome back'}</p><h1>{signup ? 'Make room for<br/><i>the wild.</i>' : 'Good to see<br/><i>you again.</i>'}</h1><p className="form-intro">{signup ? 'Create an account to share your field notes and join the conversation.' : 'Sign in to keep exploring and share your own stories.'}</p>{signup && <label>Full name<input placeholder="Your name"/></label>}<label>Email address<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="At least 8 characters"/></label>{signup && <label className="check"><input type="checkbox"/> I agree to the community guidelines</label>}<button className="dark-button full" onClick={() => go('blog')}>{signup ? 'Create my account' : 'Sign in'} <ArrowRight size={16}/></button><p className="switch">{signup ? 'Already a member?' : 'New to Udawalawe Wild?'} <button onClick={() => go(signup ? 'login' : 'signup')}>{signup ? 'Sign in' : 'Join the community'}</button></p></div></div></main> }

function NewStory({ go }: { go: (v: View) => void }) { const [mode, setMode] = useState<'story'|'review'>('story'); return <main className="new-page"><div className="new-top"><button className="back-link" onClick={() => go('blog')}><ChevronLeft size={16}/> Cancel</button><span className="save-status">Draft saved just now</span></div><div className="new-inner"><p className="eyebrow">Contribute to the journal</p><h1>Tell us what<br/><i>you saw.</i></h1><div className="toggle"><button className={mode === 'story' ? 'selected' : ''} onClick={() => setMode('story')}>Write a story</button><button className={mode === 'review' ? 'selected' : ''} onClick={() => setMode('review')}>Leave a review</button></div>{mode === 'story' ? <><label>Story title<input placeholder="Give your story a title"/></label><label>What did you see?<textarea placeholder="Start writing your field notes..." rows={7}/></label><div className="form-row"><label>Location<input placeholder="e.g. Udawalawe National Park"/></label><label>Story type<select defaultValue=""><option value="" disabled>Choose a category</option><option>Wildlife</option><option>Travel tips</option><option>Conservation</option></select></label></div><div className="upload"><Upload size={20}/><div><strong>Add photographs</strong><span>Drag and drop, or browse · Up to 10MB each</span></div><button>Browse files</button></div></> : <><label>Which place are you reviewing?<input placeholder="Search destinations"/></label><label>Your rating<div className="star-select">{[1,2,3,4,5].map(i => <Star key={i} size={29} fill={i < 5 ? 'currentColor' : 'none'} />)}</div></label><label>Your experience<textarea placeholder="What should other visitors know?" rows={7}/></label></>}<div className="submit-row"><span>Stories are reviewed before publishing.</span><button className="dark-button" onClick={() => go('blog')}>Submit for review <Send size={15}/></button></div></div></main> }

function Admin({ go }: { go: (v: View) => void }) { const [rows, setRows] = useState(['A day beside the Walawe', 'Why the langur matters', 'The road less travelled']); return <main className="admin-page"><div className="admin-header"><div><p className="eyebrow">Editor workspace</p><h1>Story queue</h1></div><button className="outline-button" onClick={() => go('blog')}>View public journal <Eye size={15}/></button></div><div className="admin-stats"><div><span>Awaiting review</span><strong>{rows.length}</strong></div><div><span>Published this month</span><strong>12</strong></div><div><span>Community members</span><strong>284</strong></div></div><section className="queue"><div className="queue-title"><h2>Needs your attention</h2><span>Newest first</span></div>{rows.map((title, i) => <div className="queue-row" key={title}><span className="queue-avatar">{String.fromCharCode(65+i)}</span><div className="queue-copy"><strong>{title}</strong><span>{['Maya de Silva','Kavindu Perera','Ishara Gunaratne'][i]} · {i+1} day{i ? 's' : ''} ago</span></div><span className="queue-type">{i === 1 ? 'Conservation' : 'Wildlife'}</span><button aria-label="Approve" onClick={() => setRows(rows.filter(r => r !== title))}><Check size={17}/></button><button aria-label="Reject"><X size={17}/></button></div>)}</section></main> }

export default function Page() { const [view, setView] = useState<View>('blog'); const go = (v: View) => setView(v); return <><Header go={go}/>{view === 'blog' && <BlogListing go={go}/>} {view === 'post' && <PostDetail go={go}/>} {view === 'login' && <Auth go={go}/>} {view === 'signup' && <Auth signup go={go}/>} {view === 'new' && <NewStory go={go}/>} {view === 'admin' && <Admin go={go}/>}<footer><span>© 2024 Udawalawe Wild</span><span>Made with respect for wild places.</span><span>Community guidelines · Privacy</span></footer></> }
